# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'NanoScan' do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # ignore all warnings from all pods
    inhibit_all_warnings!

    pod 'Charts'
    pod 'ChartsRealm'
    
    # Pods for Inspectorio
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
                    config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
                end
            end
        end
    end
end
